import React, { createContext, useContext, useState, ReactNode } from 'react';

export type LangCode = 'en' | 'hi' | 'mr' | 'bn' | 'te' | 'ta' | 'gu' | 'kn' | 'ml' | 'pa' | 'or';

export const LANGUAGES: { code: LangCode; label: string; native: string; flag: string; region: string }[] = [
  { code: 'en', label: 'English',   native: 'English',    flag: '🇬🇧', region: 'National' },
  { code: 'hi', label: 'Hindi',     native: 'हिन्दी',     flag: '🇮🇳', region: 'North' },
  { code: 'bn', label: 'Bengali',   native: 'বাংলা',      flag: '🇮🇳', region: 'East' },
  { code: 'te', label: 'Telugu',    native: 'తెలుగు',     flag: '🇮🇳', region: 'South' },
  { code: 'ta', label: 'Tamil',     native: 'தமிழ்',      flag: '🇮🇳', region: 'South' },
  { code: 'gu', label: 'Gujarati',  native: 'ગુજરાતી',    flag: '🇮🇳', region: 'West' },
  { code: 'kn', label: 'Kannada',   native: 'ಕನ್ನಡ',      flag: '🇮🇳', region: 'South' },
  { code: 'ml', label: 'Malayalam', native: 'മലയാളം',     flag: '🇮🇳', region: 'South' },
  { code: 'pa', label: 'Punjabi',   native: 'ਪੰਜਾਬੀ',     flag: '🇮🇳', region: 'North' },
  { code: 'or', label: 'Odia',      native: 'ଓଡ଼ିଆ',       flag: '🇮🇳', region: 'East' },
  { code: 'mr', label: 'Marathi',   native: 'मराठी',       flag: '🇮🇳', region: 'West' },
];

type Translations = {
  nav_who_we_are: string;
  nav_our_boards: string;
  nav_careers: string;
  nav_media: string;
  nav_governance: string;
  nav_connect: string;
  nav_sign_in: string;
  nav_get_started: string;
  nav_sign_out: string;
  nav_dashboard: string;
  hero_badge: string;
  hero_search_placeholder: string;
  hero_cta_browse: string;
  hero_cta_match: string;
  browse_all_jobs: string;
  career_paths: string;
  resume_matcher: string;
  footer_quick_links: string;
  footer_connect: string;
  about_qci: string;
  about_leadership: string;
  about_our_boards: string;
  media_press: string;
  media_publications: string;
  media_reports: string;
  media_gallery: string;
  media_videos: string;
  media_newsletter: string;
  gov_rti: string;
  gov_annual_reports: string;
  gov_audit: string;
  gov_ethics: string;
  gov_policies: string;
  gov_compliance: string;
  contact_offices: string;
  contact_email: string;
  contact_phone: string;
  contact_social: string;
  contact_feedback: string;
};

const T: Record<LangCode, Translations> = {
  en: {
    nav_who_we_are: 'Who We Are',
    nav_our_boards: 'Our Boards',
    nav_careers: 'Careers',
    nav_media: 'Media',
    nav_governance: 'Governance',
    nav_connect: 'Connect With Us',
    nav_sign_in: 'Sign In',
    nav_get_started: 'Get Started',
    nav_sign_out: 'Sign Out',
    nav_dashboard: 'Dashboard',
    hero_badge: 'Established 1997 · Ministry of Commerce & Industry',
    hero_search_placeholder: 'Role, board, skill, or department…',
    hero_cta_browse: 'Browse All Jobs',
    hero_cta_match: 'Match My Resume',
    browse_all_jobs: 'Browse All Jobs',
    career_paths: 'Career Paths',
    resume_matcher: 'Resume Matcher',
    footer_quick_links: 'Quick Links',
    footer_connect: 'Connect With Us',
    about_qci: 'About QCI',
    about_leadership: 'Leadership',
    about_our_boards: 'Our Boards',
    media_press: 'Press Releases',
    media_publications: 'Publications',
    media_reports: 'Annual Reports',
    media_gallery: 'Photo Gallery',
    media_videos: 'Videos & Webinars',
    media_newsletter: 'Newsletter',
    gov_rti: 'RTI',
    gov_annual_reports: 'Annual Reports',
    gov_audit: 'Audit Reports',
    gov_ethics: 'Ethics & Conduct',
    gov_policies: 'Policies',
    gov_compliance: 'Compliance',
    contact_offices: 'Our Offices',
    contact_email: 'Email Us',
    contact_phone: 'Call Us',
    contact_social: 'Social Media',
    contact_feedback: 'Feedback',
  },
  hi: {
    nav_who_we_are: 'हम कौन हैं',
    nav_our_boards: 'हमारे बोर्ड',
    nav_careers: 'करियर',
    nav_media: 'मीडिया',
    nav_governance: 'शासन',
    nav_connect: 'हमसे जुड़ें',
    nav_sign_in: 'साइन इन',
    nav_get_started: 'शुरू करें',
    nav_sign_out: 'साइन आउट',
    nav_dashboard: 'डैशबोर्ड',
    hero_badge: '1997 में स्थापित · वाणिज्य एवं उद्योग मंत्रालय',
    hero_search_placeholder: 'भूमिका, बोर्ड, कौशल या विभाग…',
    hero_cta_browse: 'सभी नौकरियाँ देखें',
    hero_cta_match: 'रिज्यूमे मिलाएँ',
    browse_all_jobs: 'सभी नौकरियाँ देखें',
    career_paths: 'करियर पथ',
    resume_matcher: 'रिज्यूमे मैचर',
    footer_quick_links: 'त्वरित लिंक',
    footer_connect: 'हमसे जुड़ें',
    about_qci: 'QCI के बारे में',
    about_leadership: 'नेतृत्व',
    about_our_boards: 'हमारे बोर्ड',
    media_press: 'प्रेस विज्ञप्ति',
    media_publications: 'प्रकाशन',
    media_reports: 'वार्षिक रिपोर्ट',
    media_gallery: 'फोटो गैलरी',
    media_videos: 'वीडियो और वेबिनार',
    media_newsletter: 'न्यूज़लेटर',
    gov_rti: 'आरटीआई',
    gov_annual_reports: 'वार्षिक रिपोर्ट',
    gov_audit: 'ऑडिट रिपोर्ट',
    gov_ethics: 'नैतिकता और आचार संहिता',
    gov_policies: 'नीतियाँ',
    gov_compliance: 'अनुपालन',
    contact_offices: 'हमारे कार्यालय',
    contact_email: 'ईमेल करें',
    contact_phone: 'फोन करें',
    contact_social: 'सोशल मीडिया',
    contact_feedback: 'फीडबैक',
  },
  mr: {
    nav_who_we_are: 'आम्ही कोण आहोत',
    nav_our_boards: 'आमचे मंडळ',
    nav_careers: 'करिअर',
    nav_media: 'माध्यमे',
    nav_governance: 'शासन',
    nav_connect: 'आमच्याशी संपर्क करा',
    nav_sign_in: 'साइन इन',
    nav_get_started: 'सुरुवात करा',
    nav_sign_out: 'साइन आउट',
    nav_dashboard: 'डॅशबोर्ड',
    hero_badge: '1997 मध्ये स्थापित · वाणिज्य आणि उद्योग मंत्रालय',
    hero_search_placeholder: 'भूमिका, मंडळ, कौशल्य किंवा विभाग…',
    hero_cta_browse: 'सर्व नोकऱ्या पाहा',
    hero_cta_match: 'रिझ्युमे जुळवा',
    browse_all_jobs: 'सर्व नोकऱ्या पाहा',
    career_paths: 'करिअर मार्ग',
    resume_matcher: 'रिझ्युमे मॅचर',
    footer_quick_links: 'त्वरित दुवे',
    footer_connect: 'आमच्याशी संपर्क करा',
    about_qci: 'QCI बद्दल',
    about_leadership: 'नेतृत्व',
    about_our_boards: 'आमचे मंडळ',
    media_press: 'प्रेस विज्ञप्ती',
    media_publications: 'प्रकाशने',
    media_reports: 'वार्षिक अहवाल',
    media_gallery: 'छायाचित्र दालन',
    media_videos: 'व्हिडिओ आणि वेबिनार',
    media_newsletter: 'न्यूजलेटर',
    gov_rti: 'आरटीआय',
    gov_annual_reports: 'वार्षिक अहवाल',
    gov_audit: 'लेखापरीक्षण अहवाल',
    gov_ethics: 'नैतिकता आणि आचारसंहिता',
    gov_policies: 'धोरणे',
    gov_compliance: 'अनुपालन',
    contact_offices: 'आमची कार्यालये',
    contact_email: 'ईमेल करा',
    contact_phone: 'फोन करा',
    contact_social: 'सोशल मीडिया',
    contact_feedback: 'अभिप्राय',
  },
  bn: {
    nav_who_we_are: 'আমরা কারা',
    nav_our_boards: 'আমাদের বোর্ড',
    nav_careers: 'কর্মজীবন',
    nav_media: 'মিডিয়া',
    nav_governance: 'শাসন',
    nav_connect: 'আমাদের সাথে যোগাযোগ করুন',
    nav_sign_in: 'সাইন ইন',
    nav_get_started: 'শুরু করুন',
    nav_sign_out: 'সাইন আউট',
    nav_dashboard: 'ড্যাশবোর্ড',
    hero_badge: '১৯৯৭ সালে প্রতিষ্ঠিত · বাণিজ্য ও শিল্প মন্ত্রণালয়',
    hero_search_placeholder: 'ভূমিকা, বোর্ড, দক্ষতা বা বিভাগ…',
    hero_cta_browse: 'সব চাকরি দেখুন',
    hero_cta_match: 'রিজিউমে মেলান',
    browse_all_jobs: 'সব চাকরি দেখুন',
    career_paths: 'কর্মজীবনের পথ',
    resume_matcher: 'রিজিউমে ম্যাচার',
    footer_quick_links: 'দ্রুত লিঙ্ক',
    footer_connect: 'আমাদের সাথে যোগাযোগ করুন',
    about_qci: 'QCI সম্পর্কে',
    about_leadership: 'নেতৃত্ব',
    about_our_boards: 'আমাদের বোর্ড',
    media_press: 'প্রেস বিজ্ঞপ্তি',
    media_publications: 'প্রকাশনা',
    media_reports: 'বার্ষিক প্রতিবেদন',
    media_gallery: 'ফটো গ্যালারি',
    media_videos: 'ভিডিও ও ওয়েবিনার',
    media_newsletter: 'নিউজলেটার',
    gov_rti: 'আরটিআই',
    gov_annual_reports: 'বার্ষিক প্রতিবেদন',
    gov_audit: 'অডিট প্রতিবেদন',
    gov_ethics: 'নীতি ও আচরণ',
    gov_policies: 'নীতিমালা',
    gov_compliance: 'সম্মতি',
    contact_offices: 'আমাদের অফিস',
    contact_email: 'ইমেইল করুন',
    contact_phone: 'ফোন করুন',
    contact_social: 'সোশ্যাল মিডিয়া',
    contact_feedback: 'মতামত',
  },
  te: {
    nav_who_we_are: 'మనం ఎవరు',
    nav_our_boards: 'మన బోర్డులు',
    nav_careers: 'ఉద్యోగాలు',
    nav_media: 'మీడియా',
    nav_governance: 'పాలన',
    nav_connect: 'మాతో సంప్రదించండి',
    nav_sign_in: 'సైన్ ఇన్',
    nav_get_started: 'ప్రారంభించండి',
    nav_sign_out: 'సైన్ అవుట్',
    nav_dashboard: 'డ్యాష్‌బోర్డ్',
    hero_badge: '1997లో స్థాపించబడింది · వాణిజ్య మరియు పరిశ్రమల మంత్రిత్వ శాఖ',
    hero_search_placeholder: 'పాత్ర, బోర్డు, నైపుణ్యం లేదా విభాగం…',
    hero_cta_browse: 'అన్ని ఉద్యోగాలు చూడండి',
    hero_cta_match: 'రెజ్యూమె మ్యాచ్ చేయండి',
    browse_all_jobs: 'అన్ని ఉద్యోగాలు చూడండి',
    career_paths: 'కెరీర్ మార్గాలు',
    resume_matcher: 'రెజ్యూమె మ్యాచర్',
    footer_quick_links: 'త్వరిత లింకులు',
    footer_connect: 'మాతో సంప్రదించండి',
    about_qci: 'QCI గురించి',
    about_leadership: 'నాయకత్వం',
    about_our_boards: 'మన బోర్డులు',
    media_press: 'ప్రెస్ విడుదలలు',
    media_publications: 'ప్రచురణలు',
    media_reports: 'వార్షిక నివేదికలు',
    media_gallery: 'ఫోటో గ్యాలరీ',
    media_videos: 'వీడియోలు & వెబినార్లు',
    media_newsletter: 'న్యూస్‌లెటర్',
    gov_rti: 'ఆర్‌టీఐ',
    gov_annual_reports: 'వార్షిక నివేదికలు',
    gov_audit: 'ఆడిట్ నివేదికలు',
    gov_ethics: 'నైతికత & నడవడిక',
    gov_policies: 'విధానాలు',
    gov_compliance: 'సమ్మతి',
    contact_offices: 'మన కార్యాలయాలు',
    contact_email: 'ఇమెయిల్ చేయండి',
    contact_phone: 'కాల్ చేయండి',
    contact_social: 'సోషల్ మీడియా',
    contact_feedback: 'అభిప్రాయం',
  },
  ta: {
    nav_who_we_are: 'நாங்கள் யார்',
    nav_our_boards: 'எங்கள் வாரியங்கள்',
    nav_careers: 'தொழில் வாய்ப்புகள்',
    nav_media: 'ஊடகம்',
    nav_governance: 'ஆட்சி',
    nav_connect: 'எங்களை தொடர்பு கொள்ளுங்கள்',
    nav_sign_in: 'உள்நுழைய',
    nav_get_started: 'தொடங்குங்கள்',
    nav_sign_out: 'வெளியேறு',
    nav_dashboard: 'டாஷ்போர்டு',
    hero_badge: '1997ல் நிறுவப்பட்டது · வாணிஜ்யம் மற்றும் தொழில் அமைச்சகம்',
    hero_search_placeholder: 'பதவி, வாரியம், திறன் அல்லது துறை…',
    hero_cta_browse: 'அனைத்து வேலைகளையும் காண்க',
    hero_cta_match: 'என் ரெஸ்யூமேயை பொருத்து',
    browse_all_jobs: 'அனைத்து வேலைகளையும் காண்க',
    career_paths: 'தொழில் பாதைகள்',
    resume_matcher: 'ரெஸ்யூமே மேட்சர்',
    footer_quick_links: 'விரைவு இணைப்புகள்',
    footer_connect: 'எங்களை தொடர்பு கொள்ளுங்கள்',
    about_qci: 'QCI பற்றி',
    about_leadership: 'தலைமை',
    about_our_boards: 'எங்கள் வாரியங்கள்',
    media_press: 'பத்திரிகை அறிவிப்புகள்',
    media_publications: 'வெளியீடுகள்',
    media_reports: 'வார்ஷிக அறிக்கைகள்',
    media_gallery: 'புகைப்படக் காட்சியகம்',
    media_videos: 'வீடியோக்கள் & வெபினார்கள்',
    media_newsletter: 'செய்திமடல்',
    gov_rti: 'ஆர்டிஐ',
    gov_annual_reports: 'வார்ஷிக அறிக்கைகள்',
    gov_audit: 'தணிக்கை அறிக்கைகள்',
    gov_ethics: 'நெறிமுறைகள் & நடத்தை',
    gov_policies: 'கொள்கைகள்',
    gov_compliance: 'இணக்கம்',
    contact_offices: 'எங்கள் அலுவலகங்கள்',
    contact_email: 'மின்னஞ்சல் செய்க',
    contact_phone: 'அழைக்க',
    contact_social: 'சமூக வலைப்பின்னல்',
    contact_feedback: 'கருத்து',
  },
  gu: {
    nav_who_we_are: 'અમે કોણ છીએ',
    nav_our_boards: 'અમારા બોર્ડ',
    nav_careers: 'કારકિર્દી',
    nav_media: 'મીડિયા',
    nav_governance: 'શાસન',
    nav_connect: 'અમારો સંપર્ક કરો',
    nav_sign_in: 'સાઇન ઇન',
    nav_get_started: 'શરૂ કરો',
    nav_sign_out: 'સાઇન આઉટ',
    nav_dashboard: 'ડેશબોર્ડ',
    hero_badge: '1997 માં સ્થાપિત · વાણિજ્ય અને ઉદ્યોગ મંત્રાલય',
    hero_search_placeholder: 'ભૂમિકા, બોર્ડ, કૌશલ્ય અથવા વિભાગ…',
    hero_cta_browse: 'બધી નોકરીઓ જુઓ',
    hero_cta_match: 'મારા રિઝ્યુમે સાથે મેળ',
    browse_all_jobs: 'બધી નોકરીઓ જુઓ',
    career_paths: 'કારકિર્દીના માર્ગ',
    resume_matcher: 'રિઝ્યુમે મેચર',
    footer_quick_links: 'ઝડપી લિંક',
    footer_connect: 'અમારો સંપર્ક કરો',
    about_qci: 'QCI વિશે',
    about_leadership: 'નેતૃત્વ',
    about_our_boards: 'અમારા બોર્ડ',
    media_press: 'પ્રેસ રિલીઝ',
    media_publications: 'પ્રકાશન',
    media_reports: 'વાર્ષિક અહેવાલ',
    media_gallery: 'ફોટો ગેલેરી',
    media_videos: 'વીડિયો અને વેબિનાર',
    media_newsletter: 'ન્યૂઝલેટર',
    gov_rti: 'આરટીઆઈ',
    gov_annual_reports: 'વાર્ષિક અહેવાલ',
    gov_audit: 'ઓડિટ રિપોર્ટ',
    gov_ethics: 'નૈતિકતા અને આચારસંહિતા',
    gov_policies: 'નીતિઓ',
    gov_compliance: 'અનુપાલન',
    contact_offices: 'અમારી ઓફિસ',
    contact_email: 'ઈમેઈલ કરો',
    contact_phone: 'ફોન કરો',
    contact_social: 'સોશ્યલ મીડિયા',
    contact_feedback: 'પ્રતિક્રિયા',
  },
  kn: {
    nav_who_we_are: 'ನಾವು ಯಾರು',
    nav_our_boards: 'ನಮ್ಮ ಬೋರ್ಡ್‌ಗಳು',
    nav_careers: 'ಉದ್ಯೋಗಗಳು',
    nav_media: 'ಮಾಧ್ಯಮ',
    nav_governance: 'ಆಡಳಿತ',
    nav_connect: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    nav_sign_in: 'ಸೈನ್ ಇನ್',
    nav_get_started: 'ಪ್ರಾರಂಭಿಸಿ',
    nav_sign_out: 'ಸೈನ್ ಔಟ್',
    nav_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    hero_badge: '1997 ರಲ್ಲಿ ಸ್ಥಾಪಿಸಲಾಯಿತು · ವಾಣಿಜ್ಯ ಮತ್ತು ಕೈಗಾರಿಕಾ ಸಚಿವಾಲಯ',
    hero_search_placeholder: 'ಪಾತ್ರ, ಬೋರ್ಡ್, ಕೌಶಲ್ಯ ಅಥವಾ ವಿಭಾಗ…',
    hero_cta_browse: 'ಎಲ್ಲಾ ಉದ್ಯೋಗಗಳನ್ನು ನೋಡಿ',
    hero_cta_match: 'ನನ್ನ ರೆಸ್ಯೂಮ್ ಹೊಂದಿಸಿ',
    browse_all_jobs: 'ಎಲ್ಲಾ ಉದ್ಯೋಗಗಳನ್ನು ನೋಡಿ',
    career_paths: 'ವೃತ್ತಿ ಮಾರ್ಗಗಳು',
    resume_matcher: 'ರೆಸ್ಯೂಮ್ ಮ್ಯಾಚರ್',
    footer_quick_links: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    footer_connect: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    about_qci: 'QCI ಬಗ್ಗೆ',
    about_leadership: 'ನಾಯಕತ್ವ',
    about_our_boards: 'ನಮ್ಮ ಬೋರ್ಡ್‌ಗಳು',
    media_press: 'ಪ್ರೆಸ್ ಬಿಡುಗಡೆಗಳು',
    media_publications: 'ಪ್ರಕಟಣೆಗಳು',
    media_reports: 'ವಾರ್ಷಿಕ ವರದಿಗಳು',
    media_gallery: 'ಫೋಟೋ ಗ್ಯಾಲರಿ',
    media_videos: 'ವೀಡಿಯೋಗಳು & ವೆಬಿನಾರ್‌ಗಳು',
    media_newsletter: 'ನ್ಯೂಸ್‌ಲೆಟರ್',
    gov_rti: 'ಆರ್‌ಟಿಐ',
    gov_annual_reports: 'ವಾರ್ಷಿಕ ವರದಿಗಳು',
    gov_audit: 'ಆಡಿಟ್ ವರದಿಗಳು',
    gov_ethics: 'ನೈತಿಕತೆ & ನಡವಳಿಕೆ',
    gov_policies: 'ನೀತಿಗಳು',
    gov_compliance: 'ಅನುಸರಣೆ',
    contact_offices: 'ನಮ್ಮ ಕಚೇರಿಗಳು',
    contact_email: 'ಇಮೇಲ್ ಮಾಡಿ',
    contact_phone: 'ಕರೆ ಮಾಡಿ',
    contact_social: 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ',
    contact_feedback: 'ಪ್ರತಿಕ್ರಿಯೆ',
  },
  ml: {
    nav_who_we_are: 'ഞങ്ങൾ ആരാണ്',
    nav_our_boards: 'ഞങ്ങളുടെ ബോർഡുകൾ',
    nav_careers: 'ജോലി അവസരങ്ങൾ',
    nav_media: 'മീഡിയ',
    nav_governance: 'ഭരണം',
    nav_connect: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
    nav_sign_in: 'സൈൻ ഇൻ',
    nav_get_started: 'ആരംഭിക്കൂ',
    nav_sign_out: 'സൈൻ ഔട്ട്',
    nav_dashboard: 'ഡാഷ്ബോർഡ്',
    hero_badge: '1997-ൽ സ്ഥാപിച്ചു · വാണിജ്യ-വ്യവസായ മന്ത്രാലയം',
    hero_search_placeholder: 'പദവി, ബോർഡ്, നൈപുണ്യം അല്ലെങ്കിൽ വിഭാഗം…',
    hero_cta_browse: 'എല്ലാ ജോലികളും കാണുക',
    hero_cta_match: 'എന്റെ റെസ്യൂമേ ചേർക്കുക',
    browse_all_jobs: 'എല്ലാ ജോലികളും കാണുക',
    career_paths: 'കരിയർ പാതകൾ',
    resume_matcher: 'റെസ്യൂമേ മാച്ചർ',
    footer_quick_links: 'വേഗത്തിലുള്ള ലിങ്കുകൾ',
    footer_connect: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
    about_qci: 'QCI നെ കുറിച്ച്',
    about_leadership: 'നേതൃത്വം',
    about_our_boards: 'ഞങ്ങളുടെ ബോർഡുകൾ',
    media_press: 'പ്രസ് റിലീസ്',
    media_publications: 'പ്രസിദ്ധീകരണങ്ങൾ',
    media_reports: 'വാർഷിക റിപ്പോർട്ടുകൾ',
    media_gallery: 'ഫോട്ടോ ഗ്യാലറി',
    media_videos: 'വീഡിയോകൾ & വെബിനാറുകൾ',
    media_newsletter: 'ന്യൂസ്‌ലെറ്റർ',
    gov_rti: 'ആർടിഐ',
    gov_annual_reports: 'വാർഷിക റിപ്പോർട്ടുകൾ',
    gov_audit: 'ഓഡിറ്റ് റിപ്പോർട്ടുകൾ',
    gov_ethics: 'നൈതികതയും പെരുമാറ്റവും',
    gov_policies: 'നയങ്ങൾ',
    gov_compliance: 'പാലിക്കൽ',
    contact_offices: 'ഞങ്ങളുടെ ഓഫീസുകൾ',
    contact_email: 'ഇമെയിൽ ചെയ്യുക',
    contact_phone: 'വിളിക്കുക',
    contact_social: 'സോഷ്യൽ മീഡിയ',
    contact_feedback: 'ഫീഡ്ബാക്ക്',
  },
  pa: {
    nav_who_we_are: 'ਅਸੀਂ ਕੌਣ ਹਾਂ',
    nav_our_boards: 'ਸਾਡੇ ਬੋਰਡ',
    nav_careers: 'ਕਰੀਅਰ',
    nav_media: 'ਮੀਡੀਆ',
    nav_governance: 'ਸ਼ਾਸਨ',
    nav_connect: 'ਸਾਡੇ ਨਾਲ ਜੁੜੋ',
    nav_sign_in: 'ਸਾਈਨ ਇਨ',
    nav_get_started: 'ਸ਼ੁਰੂ ਕਰੋ',
    nav_sign_out: 'ਸਾਈਨ ਆਊਟ',
    nav_dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    hero_badge: '1997 ਵਿੱਚ ਸਥਾਪਿਤ · ਵਣਜ ਅਤੇ ਉਦਯੋਗ ਮੰਤਰਾਲਾ',
    hero_search_placeholder: 'ਭੂਮਿਕਾ, ਬੋਰਡ, ਹੁਨਰ ਜਾਂ ਵਿਭਾਗ…',
    hero_cta_browse: 'ਸਾਰੀਆਂ ਨੌਕਰੀਆਂ ਦੇਖੋ',
    hero_cta_match: 'ਮੇਰਾ ਰਿਜ਼ਿਊਮੇ ਮੇਲ ਕਰੋ',
    browse_all_jobs: 'ਸਾਰੀਆਂ ਨੌਕਰੀਆਂ ਦੇਖੋ',
    career_paths: 'ਕਰੀਅਰ ਮਾਰਗ',
    resume_matcher: 'ਰਿਜ਼ਿਊਮੇ ਮੈਚਰ',
    footer_quick_links: 'ਤੁਰੰਤ ਲਿੰਕ',
    footer_connect: 'ਸਾਡੇ ਨਾਲ ਜੁੜੋ',
    about_qci: 'QCI ਬਾਰੇ',
    about_leadership: 'ਅਗਵਾਈ',
    about_our_boards: 'ਸਾਡੇ ਬੋਰਡ',
    media_press: 'ਪ੍ਰੈੱਸ ਰਿਲੀਜ਼',
    media_publications: 'ਪ੍ਰਕਾਸ਼ਨ',
    media_reports: 'ਸਾਲਾਨਾ ਰਿਪੋਰਟ',
    media_gallery: 'ਫੋਟੋ ਗੈਲਰੀ',
    media_videos: 'ਵੀਡੀਓ ਅਤੇ ਵੈਬੀਨਾਰ',
    media_newsletter: 'ਨਿਊਜ਼ਲੈਟਰ',
    gov_rti: 'ਆਰਟੀਆਈ',
    gov_annual_reports: 'ਸਾਲਾਨਾ ਰਿਪੋਰਟ',
    gov_audit: 'ਆਡਿਟ ਰਿਪੋਰਟ',
    gov_ethics: 'ਨੈਤਿਕਤਾ ਅਤੇ ਆਚਾਰ ਸੰਹਿਤਾ',
    gov_policies: 'ਨੀਤੀਆਂ',
    gov_compliance: 'ਪਾਲਣਾ',
    contact_offices: 'ਸਾਡੇ ਦਫ਼ਤਰ',
    contact_email: 'ਈਮੇਲ ਕਰੋ',
    contact_phone: 'ਫ਼ੋਨ ਕਰੋ',
    contact_social: 'ਸੋਸ਼ਲ ਮੀਡੀਆ',
    contact_feedback: 'ਫੀਡਬੈਕ',
  },
  or: {
    nav_who_we_are: 'ଆମେ କିଏ',
    nav_our_boards: 'ଆମ ବୋର୍ଡ',
    nav_careers: 'କ୍ୟାରିଅର',
    nav_media: 'ମିଡ଼ିଆ',
    nav_governance: 'ଶାସନ',
    nav_connect: 'ଆମ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ',
    nav_sign_in: 'ସାଇନ ଇନ',
    nav_get_started: 'ଆରମ୍ଭ କରନ୍ତୁ',
    nav_sign_out: 'ସାଇନ ଆଉଟ',
    nav_dashboard: 'ଡ୍ୟାସ ବୋର୍ଡ',
    hero_badge: '1997 ରେ ପ୍ରତିଷ୍ଠିତ · ବାଣିଜ୍ୟ ଏବଂ ଶିଳ୍ପ ମନ୍ତ୍ରଣାଳୟ',
    hero_search_placeholder: 'ଭୂମିକା, ବୋର୍ଡ, ଦକ୍ଷତା ବା ବିଭାଗ…',
    hero_cta_browse: 'ସମସ୍ତ ଚାକିରି ଦେଖନ୍ତୁ',
    hero_cta_match: 'ମୋ ରେଜ୍ୟୁମ ମ୍ୟାଚ କରନ୍ତୁ',
    browse_all_jobs: 'ସମସ୍ତ ଚାକିରି ଦେଖନ୍ତୁ',
    career_paths: 'କ୍ୟାରିଅର ଛାଞ୍ଚ',
    resume_matcher: 'ରେଜ୍ୟୁମ ମ୍ୟାଚର',
    footer_quick_links: 'ଦ୍ରୁତ ଲିଙ୍କ',
    footer_connect: 'ଆମ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ',
    about_qci: 'QCI ବିଷୟରେ',
    about_leadership: 'ନେତୃତ୍ୱ',
    about_our_boards: 'ଆମ ବୋର୍ଡ',
    media_press: 'ପ୍ରେସ ବିଜ୍ଞପ୍ତି',
    media_publications: 'ପ୍ରକାଶନ',
    media_reports: 'ବାର୍ଷିକ ରିପୋର୍ଟ',
    media_gallery: 'ଫଟୋ ଗ୍ୟାଲେରୀ',
    media_videos: 'ଭିଡ଼ିଓ ଓ ୱେବିନାର',
    media_newsletter: 'ନ୍ୟୁଜ ଲେଟର',
    gov_rti: 'ଆରଟିଆଇ',
    gov_annual_reports: 'ବାର୍ଷିକ ରିପୋର୍ଟ',
    gov_audit: 'ଅଡ଼ିଟ ରିପୋର୍ଟ',
    gov_ethics: 'ନୀତି ଓ ଆଚରଣ',
    gov_policies: 'ନୀତି',
    gov_compliance: 'ଅନୁପାଳନ',
    contact_offices: 'ଆମ କାର୍ଯ୍ୟାଳୟ',
    contact_email: 'ଇ-ମେଲ କରନ୍ତୁ',
    contact_phone: 'ଫୋନ କରନ୍ତୁ',
    contact_social: 'ସୋସ ମିଡ଼ିଆ',
    contact_feedback: 'ମତାମତ',
  },
};

type LanguageContextType = {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: Translations;
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: T.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const stored = (localStorage.getItem('qci_lang') as LangCode) || 'en';
  const [lang, setLangState] = useState<LangCode>(
    LANGUAGES.some(l => l.code === stored) ? stored : 'en'
  );

  const setLang = (l: LangCode) => {
    setLangState(l);
    localStorage.setItem('qci_lang', l);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
